### ISSUE TITLE
risk of suspension

### ISSUE THREAD

**Issue by elijah-wright** [stevenlafl/threads-web-client#10]
hey 👋 so I'm making my own client and I just got suspended testing it out. just wanted to bring that up here.

**Comment by stevenlafl** [comment]
@elijah-wright bummer. Thank you for telling me, as I've been helping you with testing and writing API methods back at you repo.

In my app, I've been caching requests where I can (homepage feeds on back button, notifications) and I've been closely monitoring the requests to be sure there's nothing weird happening. 

e.g. UseEffect with IsLoading states prevent dupe simultaneous requests. Also in testing I save the json responses on disk to reuse so I can be sure I don't overload it on my account before things are ready to be released.

Were you posting things a lot? What kind of activity should I avoid?

cc https://github.com/threadsjs/threads.js/issues/55#issuecomment-1633697028

**Comment by aksjdjkasdjk** [comment]
> hey 👋 so I'm making my own client and I just got suspended testing it out. just wanted to bring that up here.

Should I use it, will it suspend every account using it?

**Comment by stevenlafl** [comment]
> > hey 👋 so I'm making my own client and I just got suspended testing it out. just wanted to bring that up here.
> 
> Should I use it, will it suspend every account using it?

It's a risk as with using any undocumented APIs. In his case, he has to submit identity verification with a photo to unblock his account. For some that's unacceptable. 

I suspect he is telling me here because:
1. I help develop the API this client uses (his project). 
2. You can't direct message anyone on GitHub.

l'll reflect a readme change regarding this, so people realize the risks is non-zero. The risk is less obvious since this is a client and not an API project. I'll thank @elijah-wright for bringing this to my attention and will close this issue when the change is made.

I'll keep using it, as my activity isn't anywhere close to bot-like and this client keeps requests to the minimum

**Comment by stevenlafl** [comment]
I've updated the README with a notice and threw a LICENSE in there.

**Comment by elijah-wright** [comment]
> Were you posting things a lot? What kind of activity should I avoid?

I wasn't posting at all. I think it might have been fast reload or something like that. I only started getting issues when I tried to make profile pages.

I don't think it's an issue for most people but it's a thing that can happen. and based on what I'm seeing on the internet, it could happen to anyone even if you're not making or using a third-party client.

**Comment by stevenlafl** [comment]
That is crazy, even using the app normally, like a regular non-technical user? Wow.

**Comment by elijah-wright** [comment]
I'm not sure what I'm going to do. I have another account I can use but idk if they do IP blocks or anything like that. you said that you cache as much as possible so I don't think it's that big of a risk for you

**Comment by aksjdjkasdjk** [comment]
> > Were you posting things a lot? What kind of activity should I avoid?
> 
> I wasn't posting at all. I think it might have been fast reload or something like that. I only started getting issues when I tried to make profile pages.
> 
> I don't think it's an issue for most people but it's a thing that can happen. and based on what I'm seeing on the internet, it could happen to anyone even if you're not making or using a third-party client.

I just console.log a value in profile page and my account got suspended

**Comment by sulaimanwebdev** [comment]
> Were you posting things a lot? What kind of activity should I avoid?
> > 
> > 
> > I wasn't posting at all. I think it might have been fast reload or something like that. I only started getting issues when I tried to make profile pages.
> > I don't think it's an issue for most people but it's a thing that can happen. and based on what I'm seeing on the internet, it could happen to anyone even if you're not making or using a third-party client.
> 
> I just console.log a value in profile page and my account got suspended
