### ISSUE TITLE
Logging in issue

### ISSUE THREAD

**Issue by diyarkarimzadeh** [stevenlafl/threads-web-client#11]
I got this error message when I try to login to my account:
{"error":"Cannot read properties of undefined (reading 'bloks_payload')"}

**Comment by stevenlafl** [comment]
Hmm. I have not seen that and just tested it again. Have you verified your email, and logged into the Threads app before (on your phone)?

**Comment by diyarkarimzadeh** [comment]
> Hmm. I have not seen that and just tested it again. Have you verified your email, and logged into the Threads app before (on your phone)?

**Comment by diyarkarimzadeh** [comment]
Yes, I did that. I run the app using "npm run dev" and then I entered my threads username and password.
But I get that error every time.
Should I enter my email or username?

**Comment by stevenlafl** [comment]
Hmm, this may be an upstream issue. Can you submit an issue here: https://github.com/threadsjs/threads.js . I can see you're a developer, so this probably makes things less painful to diagnose there.

**Comment by diyarkarimzadeh** [comment]
Yea for sure, thanks
