### ISSUE TITLE
Perfomance issue

### ISSUE THREAD

**Issue by aksjdjkasdjk** [stevenlafl/threads-web-client#12]
Why it feel so slow to use?

**Comment by stevenlafl** [comment]
It's slow when you use `npm run dev` because that has to compile on-the-fly. So if you're trying to use it in production and aren't looking to write code, I'd do these steps and see how it feels:
```
npm run build
npm run start
```

**Comment by aksjdjkasdjk** [comment]
My account got suspended

**Comment by aksjdjkasdjk** [comment]
BTW can we fetch Threads data like: content likes replies without logging in?

**Comment by stevenlafl** [comment]
Sorry to hear that. They do seem to be suspending accounts that try to read a ton of data without posting, liking, or reposting anything (even if using the native app). No one knows exactly what they're looking at to judge these things yet.

Also, no, not with the API I'm using. We don't know yet if Meta will release a public API for that kind of ingest, or how much that might cost either.

**Comment by aksjdjkasdjk** [comment]
I only posted 3 to 4 Threads didn't read anything but still got suspended

**Comment by aksjdjkasdjk** [comment]
Would love to see "# tag" feature, I think this would need a database

**Comment by stevenlafl** [comment]
closing.

If you need the fastest implementation, run build.sh to build the Dockerfile yourself and then run it as shown in the docs. This is the full production optimized build.
