### ISSUE TITLE
Token is required

### ISSUE THREAD

**Issue by birobirobiro** [stevenlafl/threads-web-client#4]
When I try to log in I get this error

```bash
{error: "Token is required."}
```

**Comment by stevenlafl** [comment]
I updated the API to the newest version. Can you try `yarn install` again?

**Comment by birobirobiro** [comment]
> I updated the API to the newest version. Can you try `yarn install` again?

I updated and now the error is this one: 

```bash
{error: "Cannot read properties of null (reading '0')"}
```

**Comment by stevenlafl** [comment]
That usually indicates the password is wrong, or your account is locked out. Have you logged in with the Threads mobile app on your phone already and checked the Instagram app to be sure you aren't being requested a password reset?

Possibly related:
https://github.com/threadsjs/threads.js/issues/36

**Comment by birobirobiro** [comment]
> That usually indicates the password is wrong, or your account is locked out. Have you logged in with the Threads mobile app on your phone already and checked the Instagram app to be sure you aren't being requested a password reset?
> 
> Possibly related: [threadsjs/threads.js#36](https://github.com/threadsjs/threads.js/issues/36)

Strange, my account is opened and I confirmed the login and password and it is correct too. I'm not getting any notifications either on the Instagram or Threads app.

https://www.instagram.com/birobirobiro/
https://www.threads.net/@birobirobiro

**Comment by stevenlafl** [comment]
Are you using 2FA/MFA? I don't actually know the workflow for that, and I'm not even sure it's supported.

**Comment by birobirobiro** [comment]
> Are you using 2FA/MFA? I don't actually know the workflow for that, and I'm not even sure it's supported.

Yes, I'm using 2FA. But from what they said here it doesn't impact anything

https://github.com/threadsjs/threads.js/issues/36#issuecomment-1629286210

**Comment by birobirobiro** [comment]
> Are you using 2FA/MFA? I don't actually know the workflow for that, and I'm not even sure it's supported.

I tested with another account, even with 2FA enabled and it worked. I think my birobirobiro account must have some blocking on the Instagram API side.

**Comment by stevenlafl** [comment]
That is very strange. I'm guessing whatever caused it is probably what's happening with others in that thread. I'll have to wait as I don't have emulators setup with pinned custom certs in order to decrypt and debug of this. Thanks for the report.
